"namespace" = "red"
"type" = "red"
"variable" = "orange"
"function" = "yellow"
"type.builtin" = "red"
"string"  = "green"
"variable.parameter" = "lightblue"
"constant" = "pink"
"keyword" = "purple"
"keyword.storage" = "lightgreen"
"comment" = { fg = "grey" }
"special" = "red"

"ui.background" = { fg = "tanwhite", bg = "darkbrown" }
"ui.background.separator" = { fg = "tanwhite" }
"ui.menu" = { fg = "tanwhite", bg = "darkblue" }
"ui.menu.selected" = { fg = "darkblue", bg = "lightgreen", modifiers = ["bold"] }
"ui.popup" = { bg = "darkblue", fg="pink"}
"ui.selection" = { bg = "blue" }

"ui.window" = { fg = "brown" }

"ui.virtual" = { fg = "lightblue" }

"ui.statusline" = { fg = "tanwhite", bg="darkblue" }
"ui.statusline.inactive" = { fg = "lightbrown", bg="brown" }

"ui.cursor" = { fg = "lightgreen", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "lightgreen", modifiers = ["reversed"] }
#"ui.cursor.match" = { bg = "red", fg ="tanwhite", modifiers = ["bold"] }

"ui.text" = "tanwhite"
"ui.text.focus" = { fg = "lightgreen", bg="darkblue", modifiers = ["bold"] }

"ui.help" = { bg = "darkblue", fg = "pink" }
"ui.gutter" = { bg = "darkbrown" }
"ui.linenr" = { fg = "lightbrown" }
"ui.linenr.selected" = { fg = "lightgreen" }
"info" = "pink"
"hint" = "lightblue"
"debug" = "orange"
"warning" = "yellow"
"error" = "red"

"diagnostic" = { underline = { style = "curl"} }
"diagnostic.warning" = { fg = "yellow", underline = { color = "yellow", style = "curl"} }
"diagnostic.error" = { fg = "red", underline = { color = "red", style = "curl"} }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"

[palette]
darkbrown = "#1f1c1b"
brown = "#38302d"
lightbrown = "#887e66"
red = "#d24858"
orange = "#d27448"
yellow = "#ffd166"
tanwhite = "#ffeec0"
blue = "#2a4977"
darkblue = "#21232c"
lightblue = "#8dcae6"
pink = "#ecaad2"
green = "#83aa83"
lightgreen = "#a8f36f"
purple = "#c191ff"
grey = "#5b5e66"
